In [3]:
## instalacion de dependencias
import numpy as np
import matplotlib as mpl
import pandas as pd

## instalacion de dependeica de web scraping
from bs4 import BeautifulSoup
## para tener peticiones
import requests
#!pip install selenium
import time
from selenium import webdriver

## Carga de datos

In [4]:
urlExcel = 'content/soccer2020.xlsx'
carga = pd.read_excel(urlExcel, sheet_name="LeagueTable" )
dfExcel = pd.DataFrame(carga)
carga.head()

,Team,Rank,Points,MP,Wins,Ties,Losses,GF,GA,GD,...,Home GA,Clean Sheets Home,Away MP,Away Wins,Away Ties,Away Losses,Away GF,Away GA,Clean Sheets Away,Update Time
0,Man City,1,93,38,29,6,3,99,26,73,...,9,5,19,14,4,1,41,11,3,2022-05-26T05:22:11Z
1,Liverpool,2,92,38,28,8,2,94,26,68,...,15,7,19,13,4,2,45,17,1,2022-05-26T05:22:11Z
2,Chelsea,3,74,38,21,11,6,76,33,43,...,17,3,19,12,4,3,39,11,1,2022-05-26T05:22:11Z
3,Spurs,4,71,38,22,5,11,69,40,29,...,19,7,19,9,4,6,31,21,5,2022-05-26T05:22:11Z
4,Arsenal,5,69,38,22,3,13,61,48,13,...,22,5,19,7,8,4,23,21,3,2022-05-26T05:22:11Z